gavtate_subject:
    resource: "@gavtateBundle/Resources/config/routing/subject.yml"
    prefix:   /subject

gavtate_homepage:
    path:     /
    defaults: { _controller: gavtateBundle:Default:index }

gavtate_artist:
    path:     /artist
    defaults: { _controller: gavtateBundle:Default:artist }

gavtate_artwork:
    path:     /artwork
    defaults: { _controller: gavtateBundle:Default:artwork }

gavtate_subject:
    path:     /subjects
    defaults: { _controller: gavtateBundle:Default:subjects }

gavtate_read_subjects:
    path:     /readsubjects
    defaults: { _controller: gavtateBundle:Default:readSubjects }

gavtate_arff:
    path:     /arff
    defaults: { _controller: gavtateBundle:Default:arff }
